version: '3.8'
services:
  web_blue:
    image: myapp:blue
    container_name: django_blue
    ports:
      - "8000:8000"
    environment:
      DJANGO_ENV: blue
    networks:
      - your_network


networks:
  your_network:
    external: true
